import {
  AcUnit,
  Air,
  Bathtub,
  Bed,
  Bolt,
  Chair,
  CleaningServices,
  Countertops,
  CrisisAlert,
  CropSquare,
  DeviceThermostat,
  DoorFront,
  DynamicForm,
  Fireplace,
  Foundation,
  Grain,
  HouseSiding,
  Layers,
  LineWeight,
  LocalFireDepartment,
  Lock,
  MoreHoriz,
  Plumbing,
  Power,
  PowerOff,
  Roofing,
  ToggleOff,
  VerticalAlignTop,
  WaterDrop,
  Wc,
  Window,
} from '@mui/icons-material';

export const icons = {
  Ikkunat: Window,
  Lämmitysmuoto: LocalFireDepartment,
  Salaojat: Layers,
  Muu: MoreHoriz,
  Eristys: AcUnit,
  Sähköt: Bolt,
  Käyttövesiputket: WaterDrop,
  Viemäriputket: Plumbing,
  Lukitus: Lock,
  Ilmanvaihto: Air,
  Katto: Roofing,
  Lämmönjako: DeviceThermostat,
  Palovaroittimet: CrisisAlert,
  Rakenteet: Foundation,
  Pistorasia: Power,
  Valokatkaisia: ToggleOff,
  Julkisivu: HouseSiding,
  Eteinen: DoorFront,
  WC: Bathtub,
  Keittiö: Countertops,
  Olohuone: Chair,
  Makuuhuone: Bed,
  Sokkeli: CropSquare,
  Piipunhattu: VerticalAlignTop,
  Sähkökeskus: DynamicForm,
  Sadevesikourut: Grain,
  Kodinhoitohuone: CleaningServices,
  Savupiippu: Fireplace,
};
